### ISSUE TITLE
Resolve DNS record of connector

### ISSUE THREAD

**Issue by dereulenspiegel** [krach-protocol/smol-noice#4]
To connect to from the ESP32 to the connector the address `citynode.ingress.connctd.io` needs to be resolved to a working IPv4 address. Therefore the A record for this DNS resource needs to be queried and the answer read successfully.

**Comment by dereulenspiegel** [comment]
Implemented but needs testing/bug fixing by @SeriousD

**Comment by SeriousD** [comment]
The ESP-IDF resolves the IP Adress with no issues.
