### ISSUE TITLE
Establish a TCP connection

### ISSUE THREAD

**Issue by dereulenspiegel** [krach-protocol/smol-noice#5]
The ESP32 must successfully establish a TCP connection to the resolved server.

**Comment by dereulenspiegel** [comment]
Implemented and should work. But needs to be verified by @SeriousD

**Comment by SeriousD** [comment]
TCP connection works but not that stable. Sometimes the handshake starts, sometimes it stalls - I smell some race conditions in the statemache and network tasks.

**Comment by SeriousD** [comment]
ESP always connects to resolved server - now the handeshake is the bottleneck.
