### ISSUE TITLE
Wait for incoming data

### ISSUE THREAD

**Issue by dereulenspiegel** [krach-protocol/smol-noice#7]
After a secure, krach based connection is established, the ESP32 must wait for incoming data and not close the connection without receiving any data. `ping` commands are send about every 30 seconds (no hard scheduling), so the connection may be idle for up to about 30 seconds.

**Comment by dereulenspiegel** [comment]
The code should already behave this way, but needs verification by @SeriousD on target hardware.

**Comment by SeriousD** [comment]
works against local test server provided by connected and remote server
